// Modern CodeCollab Styles - Premium Enterprise Design
const styles = {
    // --- Color Palette (Modern Dark Theme) ---
    colors: {
        primary: '#6366F1',         // Indigo
        primaryLight: '#818CF8',    // Light Indigo
        secondary: '#1E1B4B',       // Deep Purple-Black
        accent: '#06B6D4',          // Cyan
        accentAlt: '#8B5CF6',       // Violet
        danger: '#EF4444',          // Red
        success: '#10B981',         // Green
        surface: '#0F172A',         // Almost Black
        surfaceLight: '#1E293B',    // Dark Slate
        surfaceHover: '#334155',    // Slate Hover
        text: '#F1F5F9',            // Light Slate
        textMuted: '#94A3B8',       // Muted Slate
        border: '#475569',          // Border color
    },

    // --- General Container ---
    container: {
        fontFamily: '"Inter", -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
        background: 'linear-gradient(135deg, #0F172A 0%, #1E293B 50%, #1A1F35 100%)',
        minHeight: '100vh',
        margin: 0,
        padding: 0,
        overflowY: 'visible',
        color: '#F1F5F9',
    },

    // --- Navigation Styles ---
    nav: {
        backgroundColor: '#0F172A',
        borderBottom: '1px solid #334155',
        padding: '16px 40px',
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        boxShadow: '0 10px 25px rgba(0, 0, 0, 0.4)',
        backdropFilter: 'blur(8px)',
    },
    navBrand: {
        fontSize: '26px',
        fontWeight: '800',
        background: 'linear-gradient(135deg, #6366F1 0%, #06B6D4 100%)',
        backgroundClip: 'text',
        WebkitBackgroundClip: 'text',
        WebkitTextFillColor: 'transparent',
        textDecoration: 'none',
        letterSpacing: '-0.5px',
        display: 'flex',
        alignItems: 'center',
        gap: '12px',
        fontVariantNumeric: 'tabular-nums',
    },
    navLinks: {
        display: 'flex',
        gap: '32px',
        alignItems: 'center',
    },
    navLink: {
        color: '#F1F5F9',
        textDecoration: 'none',
        fontWeight: '500',
        fontSize: '15px',
        transition: 'all 0.3s ease',
        cursor: 'pointer',
        position: 'relative',
    },
    navLinkHover: {
        color: '#06B6D4',
    },
    navButton: {
        background: 'linear-gradient(135deg, #6366F1 0%, #8B5CF6 100%)',
        color: 'white',
        border: 'none',
        padding: '10px 20px',
        borderRadius: '8px',
        cursor: 'pointer',
        fontWeight: '600',
        fontSize: '14px',
        transition: 'all 0.3s ease',
        boxShadow: '0 4px 15px rgba(99, 102, 241, 0.3)',
    },

    // --- Auth & Form Styles ---
    formContainer: {
        backgroundColor: '#1E293B',
        padding: '48px 40px',
        borderRadius: '16px',
        boxShadow: '0 20px 25px -5px rgba(0, 0, 0, 0.5), inset 0 1px 0 rgba(255,255,255,0.1)',
        border: '1px solid #334155',
        maxWidth: '420px',
        margin: '60px auto',
        backdropFilter: 'blur(10px)',
        position: 'relative',
    },
    formTitle: {
        fontSize: '32px',
        fontWeight: '800',
        background: 'linear-gradient(135deg, #6366F1 0%, #06B6D4 100%)',
        backgroundClip: 'text',
        WebkitBackgroundClip: 'text',
        WebkitTextFillColor: 'transparent',
        marginBottom: '12px',
        textAlign: 'center',
    },
    formSubtitle: {
        fontSize: '15px',
        color: '#94A3B8',
        textAlign: 'center',
        marginBottom: '32px',
        fontWeight: '500',
    },
    input: {
        width: '100%',
        padding: '12px 16px',
        marginBottom: '16px',
        border: '1px solid #475569',
        borderRadius: '10px',
        backgroundColor: '#0F172A',
        color: '#F1F5F9',
        fontSize: '14px',
        boxSizing: 'border-box',
        transition: 'all 0.3s ease',
        outline: 'none',
        fontWeight: '500',
    },
    inputFocus: {
        borderColor: '#6366F1',
        backgroundColor: '#1E293B',
        boxShadow: '0 0 0 3px rgba(99, 102, 241, 0.1)',
    },
    button: {
        width: '100%',
        padding: '12px 16px',
        marginTop: '8px',
        border: 'none',
        borderRadius: '10px',
        background: 'linear-gradient(135deg, #6366F1 0%, #8B5CF6 100%)',
        color: 'white',
        cursor: 'pointer',
        fontSize: '15px',
        fontWeight: '700',
        transition: 'all 0.3s ease',
        boxShadow: '0 4px 15px rgba(99, 102, 241, 0.3)',
        letterSpacing: '0.3px',
    },
    buttonHover: {
        transform: 'translateY(-2px)',
        boxShadow: '0 8px 25px rgba(99, 102, 241, 0.4)',
    },
    error: {
        color: '#FCA5A5',
        marginBottom: '16px',
        padding: '14px 16px',
        backgroundColor: 'rgba(239, 68, 68, 0.15)',
        borderRadius: '10px',
        fontSize: '14px',
        border: '1px solid rgba(239, 68, 68, 0.3)',
        fontWeight: '500',
    },

    // --- Dashboard Styles ---
    dashboardContainer: {
        padding: '40px 50px',
        maxWidth: '1600px',
        margin: '0 auto',
        height: 'auto',
        minHeight: '100vh',
        overflow: 'visible',
    },
    dashboardTitle: {
        fontSize: '40px',
        fontWeight: '900',
        background: 'linear-gradient(135deg, #6366F1 0%, #06B6D4 100%)',
        backgroundClip: 'text',
        WebkitBackgroundClip: 'text',
        WebkitTextFillColor: 'transparent',
        marginBottom: '12px',
    },
    dashboardSubtitle: {
        fontSize: '16px',
        fontWeight: '500',
        color: '#94A3B8',
        marginBottom: '40px',
        letterSpacing: '0.3px',
    },
    dashboardCard: {
        backgroundColor: '#1E293B',
        padding: '32px',
        borderRadius: '16px',
        boxShadow: '0 10px 25px rgba(0, 0, 0, 0.3)',
        border: '1px solid #334155',
        marginBottom: '32px',
        transition: 'all 0.3s ease',
    },
    projectList: {
        listStyle: 'none',
        padding: 0,
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fill, minmax(340px, 1fr))',
        gap: '24px',
        marginTop: '24px',
    },
    projectItem: {
        backgroundColor: '#1E293B',
        padding: '24px',
        border: '1px solid #334155',
        borderRadius: '14px',
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'space-between',
        transition: 'all 0.3s ease',
        cursor: 'pointer',
        boxShadow: '0 8px 16px rgba(0, 0, 0, 0.2)',
        position: 'relative',
        overflow: 'hidden',
    },
    projectItemHover: {
        borderColor: '#6366F1',
        boxShadow: '0 16px 32px rgba(99, 102, 241, 0.2)',
        transform: 'translateY(-6px)',
    },
    projectName: {
        margin: 0,
        fontWeight: '800',
        fontSize: '20px',
        color: '#F1F5F9',
        marginBottom: '12px',
        transition: 'color 0.3s ease',
    },
    projectDate: {
        margin: 0,
        fontSize: '13px',
        color: '#94A3B8',
        marginBottom: '20px',
        fontWeight: '500',
    },
    projectLink: {
        color: '#06B6D4',
        textDecoration: 'none',
        fontWeight: '700',
        transition: 'color 0.3s ease',
    },
    deleteButton: {
        backgroundColor: 'rgba(239, 68, 68, 0.2)',
        color: '#FF7070',
        border: '1px solid rgba(239, 68, 68, 0.3)',
        padding: '8px 14px',
        borderRadius: '8px',
        cursor: 'pointer',
        fontWeight: '600',
        fontSize: '13px',
        transition: 'all 0.3s ease',
    },
    deleteButtonHover: {
        backgroundColor: 'rgba(239, 68, 68, 0.3)',
        borderColor: 'rgba(239, 68, 68, 0.5)',
    },

    // --- Editor Layout (3-Column) ---
    editorLayoutThreeCol: {
        display: 'grid',
        gridTemplateColumns: '280px 1fr 360px',
        height: 'calc(100vh - 70px)',
        backgroundColor: '#0F172A',
        overflow: 'hidden',
    },

    // --- File List Panel ---
    fileList: {
        borderRight: '1px solid #334155',
        padding: '20px',
        backgroundColor: '#1E293B',
        overflowY: 'auto',
        display: 'flex',
        flexDirection: 'column',
    },
    fileListHeader: {
        fontSize: '15px',
        fontWeight: '800',
        color: '#F1F5F9',
        marginBottom: '20px',
        textTransform: 'uppercase',
        letterSpacing: '0.7px',
        background: 'linear-gradient(135deg, #6366F1 0%, #06B6D4 100%)',
        backgroundClip: 'text',
        WebkitBackgroundClip: 'text',
        WebkitTextFillColor: 'transparent',
    },
    fileItem: {
        padding: '12px 14px',
        cursor: 'pointer',
        borderRadius: '8px',
        marginBottom: '8px',
        fontSize: '14px',
        color: '#CBD5E1',
        transition: 'all 0.3s ease',
        wordBreak: 'break-word',
        fontWeight: '500',
    },
    fileItemHover: {
        backgroundColor: '#334155',
        color: '#F1F5F9',
    },
    activeFile: {
        padding: '12px 14px',
        cursor: 'pointer',
        borderRadius: '8px',
        backgroundColor: 'rgba(99, 102, 241, 0.15)',
        fontWeight: '700',
        color: '#06B6D4',
        borderLeft: '3px solid #06B6D4',
        paddingLeft: '11px',
        boxShadow: 'inset 0 0 12px rgba(6, 182, 212, 0.08)',
    },
    addFileButton: {
        width: '100%',
        padding: '12px',
        marginBottom: '16px',
        background: 'linear-gradient(135deg, #06B6D4 0%, #10B981 100%)',
        color: 'white',
        border: 'none',
        borderRadius: '8px',
        cursor: 'pointer',
        fontWeight: '700',
        fontSize: '14px',
        transition: 'all 0.3s ease',
        boxShadow: '0 4px 12px rgba(6, 182, 212, 0.2)',
    },
    addFileButtonHover: {
        transform: 'translateY(-2px)',
        boxShadow: '0 6px 20px rgba(6, 182, 212, 0.3)',
    },
    addFileForm: {
        display: 'flex',
        marginBottom: '16px',
        gap: '8px',
    },
    addFileInput: {
        flex: 1,
        padding: '10px 14px',
        border: '1px solid #475569',
        borderRadius: '8px',
        backgroundColor: '#0F172A',
        color: '#F1F5F9',
        fontSize: '14px',
        boxSizing: 'border-box',
        transition: 'all 0.3s ease',
        fontWeight: '500',
    },
    addFileSubmit: {
        padding: '10px 14px',
        border: 'none',
        background: 'linear-gradient(135deg, #06B6D4 0%, #10B981 100%)',
        color: 'white',
        borderRadius: '8px',
        cursor: 'pointer',
        fontWeight: '700',
        fontSize: '14px',
        transition: 'all 0.3s ease',
        boxShadow: '0 2px 8px rgba(6, 182, 212, 0.2)',
    },
    memberSection: {
        marginTop: '28px',
        paddingTop: '20px',
        borderTop: '1px solid #334155',
    },
    memberSectionTitle: {
        fontSize: '13px',
        fontWeight: '800',
        color: '#94A3B8',
        textTransform: 'uppercase',
        letterSpacing: '0.6px',
        marginBottom: '14px',
    },
    memberList: {
        listStyle: 'none',
        padding: 0,
        margin: '0 0 16px 0',
    },
    memberItem: {
        padding: '10px 12px',
        fontSize: '13px',
        color: '#CBD5E1',
        backgroundColor: '#0F172A',
        borderRadius: '8px',
        marginBottom: '8px',
        border: '1px solid #334155',
        fontWeight: '500',
        transition: 'all 0.3s ease',
    },
    editorContainer: {
        flex: 1,
        height: '100%',
    },

    // --- Chat Panel ---
    chatContainer: {
        display: 'flex',
        flexDirection: 'column',
        height: '100%',
        borderLeft: '1px solid #334155',
        backgroundColor: '#1E293B',
        minHeight: 0,
    },
    chatHeader: {
        padding: '16px 20px',
        fontWeight: '800',
        fontSize: '15px',
        backgroundColor: '#0F172A',
        borderBottom: '1px solid #334155',
        color: '#F1F5F9',
        textTransform: 'uppercase',
        letterSpacing: '0.7px',
        flexShrink: 0,
        background: 'linear-gradient(135deg, #0F172A 0%, rgba(99, 102, 241, 0.1) 100%)',
    },
    messageList: {
        flex: 1,
        padding: '16px',
        overflowY: 'auto',
        minHeight: 0,
        display: 'flex',
        flexDirection: 'column',
        gap: '12px',
    },
    messageItem: {
        padding: '14px 16px',
        borderRadius: '10px',
        backgroundColor: '#0F172A',
        maxWidth: '95%',
        wordWrap: 'break-word',
        border: '1px solid #334155',
        transition: 'all 0.3s ease',
    },
    messageAuthor: {
        color: '#06B6D4',
        fontWeight: '700',
        fontSize: '13px',
        marginBottom: '6px',
    },
    messageContent: {
        color: '#F1F5F9',
        fontSize: '14px',
        margin: '0',
        fontWeight: '500',
    },
    messageTimestamp: {
        fontSize: '12px',
        color: '#94A3B8',
        marginTop: '8px',
        display: 'block',
        fontWeight: '400',
    },
    chatForm: {
        display: 'flex',
        padding: '14px 16px',
        borderTop: '1px solid #334155',
        backgroundColor: '#0F172A',
        gap: '10px',
        flexShrink: 0,
    },
    chatInput: {
        flex: 1,
        padding: '11px 14px',
        border: '1px solid #475569',
        borderRadius: '8px',
        backgroundColor: '#1E293B',
        color: '#F1F5F9',
        fontSize: '14px',
        outline: 'none',
        transition: 'all 0.3s ease',
        fontWeight: '500',
    },
    chatButton: {
        padding: '11px 18px',
        border: 'none',
        background: 'linear-gradient(135deg, #6366F1 0%, #8B5CF6 100%)',
        color: 'white',
        borderRadius: '8px',
        cursor: 'pointer',
        fontWeight: '700',
        fontSize: '14px',
        transition: 'all 0.3s ease',
        boxShadow: '0 2px 8px rgba(99, 102, 241, 0.2)',
    },
    chatButtonHover: {
        transform: 'translateY(-2px)',
        boxShadow: '0 4px 16px rgba(99, 102, 241, 0.3)',
    },
};

export default styles;

