// VS Code-Inspired CodeCollab Styles
const styles = {
    // --- Color Palette (VS Code Dark Theme) ---
    colors: {
        primary: '#0E639C',         // VS Code Blue
        primaryLight: '#1E90FF',    // Bright Blue
        secondary: '#1E1E1E',       // VS Code Background
        accent: '#CE9178',          // VS Code Orange
        accentAlt: '#569CD6',       // VS Code Light Blue
        danger: '#F48771',          // VS Code Red
        success: '#6A9955',         // VS Code Green
        surface: '#252526',         // VS Code Surface
        surfaceLight: '#2D2D2D',    // VS Code Surface Light
        surfaceHover: '#3E3E42',    // VS Code Hover
        text: '#D4D4D4',            // VS Code Text
        textMuted: '#858585',       // VS Code Muted Text
        border: '#3E3E42',          // VS Code Border
    },

    // --- General Container ---
    container: {
        fontFamily: '"SF Mono", "Monaco", "Fira Code", "Roboto Mono", monospace, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
        background: '#1E1E1E',
        minHeight: '100vh',
        margin: 0,
        padding: 0,
        overflowY: 'visible',
        color: '#D4D4D4',
    },

    // --- Navigation Styles ---
    nav: {
        backgroundColor: '#252526',
        borderBottom: '1px solid #3E3E42',
        padding: '12px 24px',
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        boxShadow: '0 2px 8px rgba(0, 0, 0, 0.3)',
    },
    navBrand: {
        fontSize: '20px',
        fontWeight: '700',
        color: '#CE9178',
        textDecoration: 'none',
        display: 'flex',
        alignItems: 'center',
        gap: '10px',
        letterSpacing: '0px',
    },
    navLinks: {
        display: 'flex',
        gap: '24px',
        alignItems: 'center',
    },
    navLink: {
        color: '#D4D4D4',
        textDecoration: 'none',
        fontWeight: '400',
        fontSize: '13px',
        transition: 'color 0.2s ease',
        cursor: 'pointer',
        position: 'relative',
    },
    navLinkHover: {
        color: '#CE9178',
    },
    navButton: {
        background: '#0E639C',
        color: '#D4D4D4',
        border: '1px solid #0E639C',
        padding: '8px 16px',
        borderRadius: '2px',
        cursor: 'pointer',
        fontWeight: '500',
        fontSize: '12px',
        transition: 'all 0.2s ease',
    },

    // --- Auth & Form Styles ---
    formContainer: {
        backgroundColor: '#252526',
        padding: '48px 40px',
        borderRadius: '0px',
        boxShadow: '0 10px 30px rgba(0, 0, 0, 0.5)',
        border: '1px solid #3E3E42',
        maxWidth: '420px',
        margin: '60px auto',
        position: 'relative',
    },
    formTitle: {
        fontSize: '28px',
        fontWeight: '600',
        color: '#CE9178',
        marginBottom: '12px',
        textAlign: 'center',
    },
    formSubtitle: {
        fontSize: '13px',
        color: '#858585',
        textAlign: 'center',
        marginBottom: '32px',
        fontWeight: '400',
    },
    input: {
        width: '100%',
        padding: '10px 12px',
        marginBottom: '16px',
        border: '1px solid #3E3E42',
        borderRadius: '0px',
        backgroundColor: '#1E1E1E',
        color: '#D4D4D4',
        fontSize: '13px',
        boxSizing: 'border-box',
        transition: 'all 0.2s ease',
        outline: 'none',
        fontWeight: '400',
    },
    inputFocus: {
        borderColor: '#0E639C',
        backgroundColor: '#1E1E1E',
        boxShadow: '0 0 0 2px rgba(14, 99, 156, 0.2)',
    },
    button: {
        width: '100%',
        padding: '10px 16px',
        marginTop: '8px',
        border: 'none',
        borderRadius: '0px',
        background: '#0E639C',
        color: '#D4D4D4',
        cursor: 'pointer',
        fontSize: '13px',
        fontWeight: '500',
        transition: 'all 0.2s ease',
    },
    buttonHover: {
        background: '#1177BB',
    },
    error: {
        color: '#F48771',
        marginBottom: '16px',
        padding: '12px 14px',
        backgroundColor: 'rgba(244, 135, 113, 0.1)',
        borderRadius: '0px',
        fontSize: '12px',
        border: '1px solid #F48771',
        fontWeight: '400',
    },

    // --- Dashboard Styles ---
    dashboardContainer: {
        padding: '32px 40px',
        maxWidth: '1400px',
        margin: '0 auto',
        height: 'auto',
        minHeight: 'calc(100vh - 60px)',
        overflow: 'visible',
        backgroundColor: '#1E1E1E',
    },
    dashboardTitle: {
        fontSize: '32px',
        fontWeight: '600',
        color: '#CE9178',
        marginBottom: '8px',
    },
    dashboardSubtitle: {
        fontSize: '13px',
        fontWeight: '400',
        color: '#858585',
        marginBottom: '40px',
    },
    dashboardCard: {
        backgroundColor: '#252526',
        padding: '24px',
        borderRadius: '0px',
        boxShadow: '0 4px 12px rgba(0, 0, 0, 0.3)',
        border: '1px solid #3E3E42',
        marginBottom: '32px',
        transition: 'all 0.2s ease',
    },
    projectList: {
        listStyle: 'none',
        padding: 0,
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fill, minmax(320px, 1fr))',
        gap: '20px',
        marginTop: '20px',
    },
    projectItem: {
        backgroundColor: '#252526',
        padding: '20px',
        border: '1px solid #3E3E42',
        borderRadius: '0px',
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'space-between',
        transition: 'all 0.2s ease',
        cursor: 'pointer',
        boxShadow: '0 4px 8px rgba(0, 0, 0, 0.2)',
        position: 'relative',
        overflow: 'hidden',
    },
    projectItemHover: {
        borderColor: '#0E639C',
        boxShadow: '0 8px 16px rgba(14, 99, 156, 0.2)',
        backgroundColor: '#2D2D2D',
    },
    projectName: {
        margin: 0,
        fontWeight: '600',
        fontSize: '16px',
        color: '#D4D4D4',
        marginBottom: '10px',
        transition: 'color 0.2s ease',
    },
    projectDate: {
        margin: 0,
        fontSize: '12px',
        color: '#858585',
        marginBottom: '16px',
        fontWeight: '400',
    },
    projectLink: {
        color: '#CE9178',
        textDecoration: 'none',
        fontWeight: '500',
        transition: 'color 0.2s ease',
    },
    deleteButton: {
        backgroundColor: 'transparent',
        color: '#F48771',
        border: '1px solid #F48771',
        padding: '6px 12px',
        borderRadius: '0px',
        cursor: 'pointer',
        fontWeight: '500',
        fontSize: '12px',
        transition: 'all 0.2s ease',
    },
    deleteButtonHover: {
        backgroundColor: '#F48771',
        color: '#1E1E1E',
    },

    // --- Editor Layout (3-Column) ---
    editorLayoutThreeCol: {
        display: 'grid',
        gridTemplateColumns: '260px 1fr 300px',
        height: 'calc(100vh - 60px)',
        backgroundColor: '#1E1E1E',
        overflow: 'hidden',
    },

    // --- File List Panel ---
    fileList: {
        borderRight: '1px solid #3E3E42',
        padding: '16px 0',
        backgroundColor: '#252526',
        overflowY: 'auto',
        display: 'flex',
        flexDirection: 'column',
    },
    fileListHeader: {
        fontSize: '12px',
        fontWeight: '700',
        marginBottom: '16px',
        textTransform: 'uppercase',
        letterSpacing: '0.5px',
        paddingLeft: '16px',
        paddingRight: '16px',
        color: '#CE9178',
    },
    fileItem: {
        padding: '8px 16px',
        cursor: 'pointer',
        borderRadius: '0px',
        marginBottom: '0px',
        fontSize: '12px',
        color: '#858585',
        transition: 'all 0.1s ease',
        wordBreak: 'break-word',
        fontWeight: '400',
        borderLeft: '3px solid transparent',
    },
    fileItemHover: {
        backgroundColor: '#2D2D2D',
        color: '#D4D4D4',
    },
    activeFile: {
        padding: '8px 16px',
        cursor: 'pointer',
        borderRadius: '0px',
        backgroundColor: 'rgba(14, 99, 156, 0.1)',
        fontWeight: '500',
        color: '#CE9178',
        borderLeft: '3px solid #CE9178',
        paddingLeft: '13px',
        boxShadow: 'none',
    },
    addFileButton: {
        width: 'calc(100% - 32px)',
        padding: '8px 12px',
        marginBottom: '12px',
        marginLeft: '16px',
        marginRight: '16px',
        background: '#0E639C',
        color: '#D4D4D4',
        border: 'none',
        borderRadius: '0px',
        cursor: 'pointer',
        fontWeight: '500',
        fontSize: '12px',
        transition: 'all 0.2s ease',
    },
    addFileButtonHover: {
        background: '#1177BB',
    },
    addFileForm: {
        display: 'flex',
        marginBottom: '12px',
        marginLeft: '16px',
        marginRight: '16px',
        gap: '6px',
    },
    addFileInput: {
        flex: 1,
        padding: '8px 10px',
        border: '1px solid #3E3E42',
        borderRadius: '0px',
        backgroundColor: '#1E1E1E',
        color: '#D4D4D4',
        fontSize: '12px',
        boxSizing: 'border-box',
        transition: 'all 0.2s ease',
        fontWeight: '400',
    },
    addFileSubmit: {
        padding: '8px 10px',
        border: 'none',
        background: '#0E639C',
        color: '#D4D4D4',
        borderRadius: '0px',
        cursor: 'pointer',
        fontWeight: '600',
        fontSize: '12px',
        transition: 'all 0.2s ease',
    },
    memberSection: {
        marginTop: '20px',
        paddingTop: '16px',
        paddingLeft: '16px',
        paddingRight: '16px',
        borderTop: '1px solid #3E3E42',
    },
    memberSectionTitle: {
        fontSize: '11px',
        fontWeight: '700',
        textTransform: 'uppercase',
        letterSpacing: '0.5px',
        marginBottom: '12px',
        color: '#CE9178',
    },
    memberList: {
        listStyle: 'none',
        padding: 0,
        margin: '0 0 12px 0',
    },
    memberItem: {
        padding: '8px 10px',
        fontSize: '12px',
        color: '#858585',
        backgroundColor: '#1E1E1E',
        borderRadius: '0px',
        marginBottom: '6px',
        border: '1px solid #3E3E42',
        fontWeight: '400',
        transition: 'all 0.2s ease',
    },
    editorContainer: {
        flex: 1,
        height: '100%',
    },

    // --- Chat Panel ---
    chatContainer: {
        display: 'flex',
        flexDirection: 'column',
        height: '100%',
        borderLeft: '1px solid #3E3E42',
        backgroundColor: '#252526',
        minHeight: 0,
    },
    chatHeader: {
        padding: '12px 16px',
        fontWeight: '700',
        fontSize: '12px',
        backgroundColor: '#1E1E1E',
        borderBottom: '1px solid #3E3E42',
        color: '#CE9178',
        textTransform: 'uppercase',
        letterSpacing: '0.5px',
        flexShrink: 0,
    },
    messageList: {
        flex: 1,
        padding: '12px 16px',
        overflowY: 'auto',
        minHeight: 0,
        display: 'flex',
        flexDirection: 'column',
        gap: '8px',
    },
    messageItem: {
        padding: '10px 12px',
        borderRadius: '0px',
        backgroundColor: '#1E1E1E',
        maxWidth: '100%',
        wordWrap: 'break-word',
        border: '1px solid #3E3E42',
        transition: 'all 0.2s ease',
        fontSize: '12px',
    },
    messageAuthor: {
        color: '#CE9178',
        fontWeight: '600',
        fontSize: '11px',
        marginBottom: '4px',
    },
    messageContent: {
        color: '#D4D4D4',
        fontSize: '12px',
        margin: '0',
        fontWeight: '400',
        lineHeight: '1.4',
    },
    messageTimestamp: {
        fontSize: '11px',
        color: '#858585',
        marginTop: '6px',
        display: 'block',
        fontWeight: '400',
    },
    chatForm: {
        display: 'flex',
        padding: '12px 16px',
        borderTop: '1px solid #3E3E42',
        backgroundColor: '#1E1E1E',
        gap: '8px',
        flexShrink: 0,
    },
    chatInput: {
        flex: 1,
        padding: '8px 10px',
        border: '1px solid #3E3E42',
        borderRadius: '0px',
        backgroundColor: '#252526',
        color: '#D4D4D4',
        fontSize: '12px',
        outline: 'none',
        transition: 'all 0.2s ease',
        fontWeight: '400',
    },
    chatButton: {
        padding: '8px 14px',
        border: 'none',
        background: '#0E639C',
        color: '#D4D4D4',
        borderRadius: '0px',
        cursor: 'pointer',
        fontWeight: '500',
        fontSize: '12px',
        transition: 'all 0.2s ease',
    },
    chatButtonHover: {
        background: '#1177BB',
    },
};

export default styles;

